# Generated by Django 5.0.2 on 2025-04-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
